@startuml
Project <-up- Team : associated <
Team <- ProjectManager : leads <
Project <- ProjectManager : manages <
Project -down-> System : produce(Requirments) >
Developer -> Team : 0..* 
(System, Project) .. Requirements



class Project {
    name : String
    startDate : Date
    endDate : Date
}

class System {
    percentage : Int
    description : String
}

class Requirements {
    percentage : Int
    description : String
}

class ProjectManager {
    name : String
    telephone : Int
    team : String
}
ProjectManager : startproject(Project)
ProjectManager : Terminate(Project) 

@enduml

@startuml
hide empty description

[*] --> Unmodified : Clone
Unmodified --> Modified : Edit
Modified --> Staged : Add
Staged --> Unmodified : Commit

@enduml

@startuml
hide empty description

[*] --> Untracked : Create file
Untracked --> Staged : Add
Staged --> Unmodified : Commit
Unmodified --> Modified : Edit

@enduml